### ISSUE TITLE
wp-serverinfo into Dutch

### ISSUE THREAD

**Issue by ghost** [lesterchan/wp-serverinfo#4]
Hi,

I have translated my version of wp-serverinfo into Dutch.
It could be a little different as your version.

Hopefully do you see the changes.

This can be found at https://github.com/edwarddekker/wp-serverinfo

Feel free to copy and make a extension with more languages.

Best of Regards,
Edward

**Comment by lesterchan** [comment]
The plugin is using PolyGot to translate https://translate.wordpress.org/projects/wp-plugins/wp-serverinfo

**Comment by ghost** [comment]
Than you should update also your credentials.

**Comment by lesterchan** [comment]
Thanks, just did it e1bc54f20207654487d8fbb602c1f72e5ae3dff1
