### ISSUE TITLE
PHP 7.1 warnings

### ISSUE THREAD

**Issue by knutsp** [lesterchan/wp-serverinfo#6]
> PHP Warning:  A non-numeric value encountered in /wp-content/plugins/wp-serverinfo/wp-serverinfo.php on line 462
> PHP Warning:  A non-numeric value encountered in /wp-content/plugins/wp-serverinfo/wp-serverinfo.php on line 479

**Comment by lesterchan** [comment]
https://github.com/lesterchan/wp-serverinfo/commit/e1d14fa41b51e69e2eb56814b484cf8486a890fc
